# Intro

We are familiar with NumPy and its `ndarray` object, which enables efficient storage and manipulation of dense typed arrays in Python. Now we build on this knowledge by looking in depth at the *data structures* provided by the Pandas library.

Pandas is a newer package built on top of NumPy that provides an efficient implementation of a `DataFrame`. `DataFrames` are essentially multidimensional arrays with attatched row and column labels, ofen with heterogeneous types and/or missing data.

# Chapter 13 : Introducing Pandas Objects

In [2]:
# start code with standard NumPy and Pandas imports
import numpy as np
import pandas as pd

## 13.1 The Pandas `Series` Object
---

A Pandas `Series` is a 1-d array of indexed data. It can be created from a list or array as follows:

In [3]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

The `Series` combines a sequence of values with an explicit sequence of indices which we can access with the **`values`** and **`index`** attributes. The `values` are simply a familiar NumPy array.

In [4]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

The `index` is an array-like object of type `pd.Index`.

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

Data can be accessed by the associated index via the familiar Python square-bracket notation.

In [7]:
print(data[1], '\n')
print(data[1:3])

0.5 

1    0.50
2    0.75
dtype: float64


### Series as Generalized NumPy Array

The difference between a `Series` and a NumPy array is that NumPy arrays have an *implicity defined* integer index to access values while the Pandas `Series` has an *explicitly defined* index associated with values.

This explicit index definition gives the `Series` object capabilities. For example, the index need not be an integer, but can consist of values of any desired type.

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [9]:
# item access works as expected
data['b']

0.5

In [11]:
# noncontiguous or nonsequential indices
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = [2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [12]:
data[5]

0.5

### Series as Specialized Dictionary

You can think of a Pandas `Series` as a specialization of a Python dictionary. A dictionary is a structure that maps arbitrary kesy to a set of arbitrary values, and a `Series` is a structure that maps typed keys to a set of typed values.

The `Series`-as-dictionary analogy can be made clear by constructing a `Series` object directly from a Python dictionary.

In [13]:
population_dict = {'California': 39538223, 'Texas': 29145505,
                   'Florida': 21538187, 'New York': 20201249,
                   'Pennsylvania': 13002700}
population = pd.Series(population_dict)
population

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
dtype: int64

In [14]:
population['California']

39538223

In [15]:
# Unlike dictionary, Series support array-style operations
population['California':'Florida']

California    39538223
Texas         29145505
Florida       21538187
dtype: int64

### Constructing Series Objects

We've already seen a few ways of constructing a pandas `Series` from scratch. Al of them are some version of the following:
```
pd.Series(data, index = index)
```
where `index` is an optional argument, and `data` can be one of many entities.

For example, `data` can be a list or NumPy array, in which case `index defaults to an integer sequence.

In [16]:
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [17]:
# data can be a scalar, which is repeated to fill a specified index
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [18]:
# can be a dictionary, index defaults to dictionary keys
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [19]:
# index can be explicity set to control order or subset of keys used
pd.Series({2:'a', 1:'b', 3:'c'}, index = [1, 2])

1    b
2    a
dtype: object

## 13.2 The Pandas `DataFrame` Object
---

The `DataFrame` can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dicionary.

### DataFrame as Generalized NumPy Array

If a `Series` is an analog of a 1-d array with explicit indices, a `DataFrame` is an analog of a 2-d array with explicit row and column indices. Think of a `DataFrame` as a sequence of aligned `Series` objects. By "aligned" we mean they share the same index.

To demonstrate, construct a new `Series` listing the area of five states in the previous section (in square km).

In [22]:
area_dict = {'California': 423967, 'Texas': 695662, 'Florida': 170312,
             'New York': 141297, 'Pennsylvania': 119280}
area = pd.Series(area_dict)
area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
dtype: int64

Now that we have this along with the `population` `Series` from before, we can use a dictionary to construct a single 2-d object containing this information.

In [23]:
states = pd.DataFrame({'population':population, 'area':area})
states

population    area
California      39538223  423967
Texas           29145505  695662
Florida         21538187  170312
New York        20201249  141297
Pennsylvania    13002700  119280

In [24]:
# just like Series, DataFrame has index attribute
states.index

Index(['California', 'Texas', 'Florida', 'New York', 'Pennsylvania'], dtype='object')

### DataFrame as Specialized Dictionary

We can also think of a `DataFrame` as a specialization of a dictionary. Where a dictionary maps a key to a value, a `DataFrame` maps a column name to a `Series` of column data. For example, asking for the `area` attribute returns the `Series` object containing the areas.

In [27]:
states['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

### Constructing DataFrame Objects

#### From a single Series object

A `DataFrame` is a collection of `Series` objects, and a single-column `DataFrame` can be constructed from a single `Series`.

In [28]:
pd.DataFrame(population, columns = ['population'])

population
California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700

#### From a list of dicts

Any list of dictionaries can be made into a DataFrame. We'll use a simple list comprehension to create some data.

In [30]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

Even if some keys in the dictionary are missing, Pandas will fill them in with `NaN` values.

In [31]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b':3, 'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

#### From a dictionary of Series objects

A `DataFrame` can be constructed from a dictionary of `Series` objects as well.

In [32]:
pd.DataFrame({'population': population, 'area': area})

population    area
California      39538223  423967
Texas           29145505  695662
Florida         21538187  170312
New York        20201249  141297
Pennsylvania    13002700  119280

#### From a 2-d NumPy array

Given a 2-d array of data, we can create a `DataFrame` with any specified column and index names. If ommited, an integer index will be used for each.

In [33]:
pd.DataFrame(np.random.rand(3,2),
             columns = ['foo', 'bar'],
             index = ['a', 'b', 'c'])

foo       bar
a  0.961252  0.945854
b  0.357918  0.973797
c  0.947724  0.232175

#### From a NumPy structured Array

Structured arrays were covered in Chapter 12. A Pandas `DataFrame` operates much like a structured array and can be created directly from one.

In [34]:
A = np.zeros(3, dtype = [('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [35]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## 13.3 The Pandas `Index` Object
---

The `Index` object can be thought of either as an *immutable array* or as an *ordered set*. Let's construct an `Index from a list of integers.

In [36]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

### Index as Immutable Array 

The `Index` in many ways operates like an array. We can use standard Python indexing notation to retrieve values or slices.

In [37]:
ind[1]

3

In [38]:
ind[::2]

Index([2, 5, 11], dtype='int64')

In [40]:
# also has many of the attributes familiar from Python arrays
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


One difference is that indices are immutable - that is they cannot be modified via normal means.

In [41]:
ind[1] = 0

TypeError: Index does not support mutable operations

### Index as Ordered Set

The `Index` object follows many of the conventions used by Python's built-in `set` data structure, so that unions, intersections, differences, and other combinations can be computed in a familiar way.

In [42]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [43]:
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

In [45]:
indA.union(indB)

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [47]:
indA.symmetric_difference(indB)

Index([1, 2, 9, 11], dtype='int64')

# Chapter 14 : Data Indexing and Selection

## 14.1 Data Selection in Series
---

A `Series` object acts in many ways like a 1-d NumPy array, and in many ways like a standard Python dictionary.

### Series as Dicitonary

Like a dictionary, the `Series` object provides a mapping from a collection of keys to a collection of values.

In [1]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [2]:
data['b']

0.5

In [3]:
# can use dictionary-like Python expressions to examine keys/indices and values
'a' in data

True

In [4]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [5]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

`Series` objects can be modified with dictionary-like syntax. You can extend a `Series` by assigning to a new index value.

In [6]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### Series as 1-D Array

A `Series` builds on this dictionary-like interface and provides array-style item selection via the same basic mechanisms as NumPy arrays - that is, slicing, masking, and fancy indexing.

In [7]:
# slicing by explicit index
data['a' : 'c']

a    0.25
b    0.50
c    0.75
dtype: float64

Note that when slicing with an explicit index, the final index is *included* in the slice, while when slicing with an implicit inex, the final index is *excluded* from the slice.

In [8]:
# slicing by explicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [9]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [10]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

### Indexers: `loc` and `iloc`

If your `Series` has an explicit integer index, an indexing operation such as `data[1]` will use the explicit indices, whiling a slicing operation like `data[1:3]` will use implicit Python-style indices.

In [11]:
data = pd.Series(['a', 'b', 'c'], index = [1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [12]:
# explicit index when indexing
data[1]

'a'

In [13]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

Because of this potential confusion in the case of integer indexes, Pandas provieds some special *indexer* attributes that explicitly expose certain indexing schemes.

The ***`loc`*** attribute allows indexing and slicing that always references the explicit index.

In [14]:
data.loc[1]

'a'

In [15]:
data.loc[1:3]

1    a
3    b
dtype: object

The ***`iloc`*** allows indexing and slicing that always references the implicit Python-style index.

In [16]:
data.iloc[1]

'b'

In [17]:
data.iloc[1:3]

3    b
5    c
dtype: object

One guiding principle of Python code is that *"explicit is better than implicit."* The explicit nature of `loc` and `iloc` makes them helpful in maintaining clean and readable code; especially in the case of integer indexes, using them consistently can prevent subtle bugs due to the mixed indexing/slicing convention.

## 14.2 Data Selection in DataFrames
---

Recall that a `DataFrame` acts in many ways like a 2-d or structured array, and in other ways like a dictionary of `Series` structures sharing the same index.

### DataFrame as Dictionary

In [18]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'Florida': 170312, 'New York': 141297,
                  'Pennsylvania': 119280})
pop = pd.Series({'California': 39538223, 'Texas': 29145505,
                 'Florida': 21538187, 'New York': 20201249,
                 'Pennsylvania': 13002700})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

The individual `Series` that make up the columns of the `DataFrame` can be accessed via dictionary-style indexing of the column name:

In [19]:
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [20]:
# equivalently, attribute-style access with column names that are strings
data.area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

Attribute-style does not work if the column names are not strings, or if the column names conflict with `DataFrame` methods. For instance, `data.pop` will not work since `DataFrame` has a `pop` method.

You should avoid the temptation to try column assignment via attributes though.

Dictionary-style syntax can also be used to modify the object, in this case adding a new column:

In [21]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

### DataFrame as 2-D Array

We can also view the `DataFrame` as an enhanced 2-d array. WE can examine the ray underlying data using the values attribute.

In [22]:
data.values

array([[4.23967000e+05, 3.95382230e+07, 9.32577842e+01],
       [6.95662000e+05, 2.91455050e+07, 4.18960717e+01],
       [1.70312000e+05, 2.15381870e+07, 1.26463121e+02],
       [1.41297000e+05, 2.02012490e+07, 1.42970120e+02],
       [1.19280000e+05, 1.30027000e+07, 1.09009893e+02]])

With this picture in mind, many familiar array-like operations can be done on the `DataFrame` itself. For instance, we can transpose the full `DataFrame` to swap rows and columns:

In [23]:
data.T

California         Texas       Florida      New York  Pennsylvania
area     4.239670e+05  6.956620e+05  1.703120e+05  1.412970e+05  1.192800e+05
pop      3.953822e+07  2.914550e+07  2.153819e+07  2.020125e+07  1.300270e+07
density  9.325778e+01  4.189607e+01  1.264631e+02  1.429701e+02  1.090099e+02

Passing a single index to an array accesses a row.

In [24]:
data.values[0]

array([4.23967000e+05, 3.95382230e+07, 9.32577842e+01])

Passing a single "index" to a `DataFrame` accesses a column.

In [25]:
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

For array-style indexing, we need another conventoin. Here Pandas again uses the `loc` and `iloc` indexers mentioned earlier. Using the `iloc` indexer, we can index the underlying array as if it were a simple NumPy array (using the implicit Python-style index), but the `DataFrame` index and column labels are maintained in the result.

In [26]:
data.iloc[:3, :2]

area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

Similarly, using `loc` we can index the underlying data using the explict index and column names.

In [27]:
data.loc[:'Florida', :'pop']

area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

Any of the familiar NumPy-style data access patterns can be used within these indexers.

In [28]:
# can combine masking and fancy indexing
data.loc[data.density > 120, ['pop', 'density']]

pop     density
Florida   21538187  126.463121
New York  20201249  142.970120

Any of these indexing conventions may also be used to set or modify values.

In [30]:
data.iloc[0, 2] = 90
data

area       pop     density
California    423967  39538223   90.000000
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

### Additional Indexing Conventions

*Indexing* refers to columns, *slicing* refers to rows.

In [31]:
data['Florida':'New York']

area       pop     density
Florida   170312  21538187  126.463121
New York  141297  20201249  142.970120

Such slices can also refer to rows by number rather than by index.

In [32]:
data[1:3] 

area       pop     density
Texas    695662  29145505   41.896072
Florida  170312  21538187  126.463121

Direct masking operations are interpreted row-wise rather than column-wise.

In [39]:
data[data.density > 120]

area       pop     density
Florida   170312  21538187  126.463121
New York  141297  20201249  142.970120

# Chapter 15 : Operating on Data in Pandas

For unary operations, the ufuncs will *preserve index and column labels* in the output. For binary operations such as addition and multiplication, Pandas will automatically *align indices* when passing the objects to the ufunc.

## 15.1 Ufuncs : Index Preservation
---

Because Pandas is designed to work with NumPy, any NumPy ufunc will work on Pandas `Series` and `DataFrame` objects.

In [1]:
import pandas as pd
import numpy as np

In [2]:
rng = np.random.default_rng(42)
ser = pd.Series(rng.integers(0,10,4))
ser

0    0
1    7
2    6
3    4
dtype: int64

In [3]:
df = pd.DataFrame(rng.integers(0, 10, (3,4)),
                  columns = ['A', 'B', 'C', 'D'])
df

A  B  C  D
0  4  8  0  6
1  2  0  5  9
2  7  7  7  7

If we apply a NumPy ufunc on either of these objects, the result will be another Pandas object *with the indices preserved*.

In [4]:
np.exp(ser)

0       1.000000
1    1096.633158
2     403.428793
3      54.598150
dtype: float64

In [5]:
np.sin(df * np.pi / 4)

A             B         C         D
0  1.224647e-16 -2.449294e-16  0.000000 -1.000000
1  1.000000e+00  0.000000e+00 -0.707107  0.707107
2 -7.071068e-01 -7.071068e-01 -0.707107 -0.707107

## 15.2 Ufuncs : Index Alignment
---

On binary operations on two `Series` or `DataFrame` objects, Pandas will align indices in the process of performing the operation. This is very convenient when working with incomplete data.

### Index Alignment in Series

In [6]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 39538223, 'Texas': 29145505,
                        'Florida': 21538187}, name='population')

In [7]:
population / area

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64

The resulting array contains the *union* of indices of the two input arrays, which could be determined directl from these indices.

In [9]:
area.index.union(population.index)

Index(['Alaska', 'California', 'Florida', 'Texas'], dtype='object')

Any item for which one or the other does not have an entry is marked with a `NaN`, or "Not a Number", which is how Pandas marks missing data.

This index matching is implemented this way for any of Python's built-in arithmetic expressions; any missing values are marked by `NaN`.

In [10]:
A = pd.Series([2, 4, 6], index = [0, 1, 2])
B = pd.Series([1, 3, 5], index = [1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

If using `NaN` is not desired, the fill value can be modified using appropriate object methods in place of the operators.

In [11]:
A.add(B, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Index Alignment in DataFrames

A similar type of alignment takes place for *both* columns and indices when performing operations on `DataFrame` objects.

In [26]:
A = pd.DataFrame(rng.integers(0, 20, (2,2)), 
                 columns = ['a', 'b'])
A

a   b
0  19   8
1   6  18

In [27]:
B = pd.DataFrame(rng.integers(0, 10, (3,3)),
                 columns = ['b', 'a', 'c'])
B

b  a  c
0  3  0  4
1  7  1  4
2  1  6  4

In [28]:
A + B

a     b   c
0  19.0  11.0 NaN
1   7.0  25.0 NaN
2   NaN   NaN NaN

In [31]:
# filling value to not use NaN
A.add(B, fill_value = A.values.mean())

a      b      c
0  19.00  11.00  16.75
1   7.00  25.00  16.75
2  18.75  13.75  16.75

|Python operator|Pandas method(s)|
|---------------|----------------|
|+|add|
|-|sub, subtract|
|*|mul, multiply|
|/|truediv, div, divide|
|//|floordiv|
|%|mod|
|**|pow|

## 15.3 Ufuncs: Operations Between DataFrames and Series
---

When performing operations between a `DataFrame` and a `Series`, the index and column alignment is maintained, and the result is similar to operations between a 2-d and 1-d array.

In [33]:
A = rng.integers(10, size = (3, 4))
A

array([[7, 8, 4, 8],
       [8, 3, 8, 2],
       [2, 6, 6, 1]], dtype=int64)

In [34]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 1, -5,  4, -6],
       [-5, -2,  2, -7]], dtype=int64)

According to NumPy's broadcasting rules (Ch 8), subtraction between a 2-d array and one of its rows is applied row wise.

In Pandas, the convention similarly operates row-wise by default.

In [35]:
df = pd.DataFrame(A, columns = ['Q', 'R', 'S', 'T'])
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  1 -5  4 -6
2 -5 -2  2 -7

To operate column-wise, use the object methods mentioned earlier while specifying the `axis` keyword.

In [36]:
df.sub(df['R'], axis = 0)

Q  R  S  T
0 -1  0 -4  0
1  5  0  5 -1
2 -4  0  0 -5

Note that these `DataFrame`\`Series` operations, like the operations discuessed previously, will automatically align indices between two elements.

In [38]:
halfrow = df.iloc[0, ::2]
halfrow

Q    7
S    4
Name: 0, dtype: int64

In [39]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  1.0 NaN  4.0 NaN
2 -5.0 NaN  2.0 NaN

This preservation and alignment of indices and columns means that operations on data in Pandas will always maintain the data context, which prevents the common errors that might arise when working with heterogeneous and/or misaligned data in raw NumPy arrays.

# Chapter 16 : Handling Missing Data 

## 16.1 Trade-offs in Missing Data Conventions
---

## 16.2 Missing Data in Pandas
---

### `None` as a Sentinel View

### `NaN` : Missing Numerical Data

### `NaN` and `None` in Pandas

## 16.3 Pandas Nullable Dtypes
---

## 16.4 Operating on Null Values
---

### Detecting Null Values

### Dropping Null Values

### Filling Null Values

# Ch 17 : Hierarchical Indexing